/**
 * Scan universe: liquid NSE large and mid caps (Nifty 200 core, plus liquid
 * F&O names). Sector tags and F&O membership are curated and can drift from
 * NSE's occasional revisions; fix entries here as needed.
 *
 * Tuple layout keeps the file compact: [symbol, company, sector, isFno]
 */
export type Sector =
  | "Banks"
  | "Financial Services"
  | "IT"
  | "Pharma"
  | "Healthcare"
  | "FMCG"
  | "Auto"
  | "Metals"
  | "Energy"
  | "Power"
  | "Capital Goods"
  | "Cement"
  | "Chemicals"
  | "Realty"
  | "Infra"
  | "Consumer"
  | "Telecom"
  | "Media"
  | "Logistics";

type Entry = [symbol: string, name: string, sector: Sector, fno: boolean, aliases?: string[]];

const ENTRIES: Entry[] = [
  // Banks
  ["HDFCBANK", "HDFC Bank", "Banks", true],
  ["ICICIBANK", "ICICI Bank", "Banks", true],
  ["SBIN", "State Bank of India", "Banks", true],
  ["KOTAKBANK", "Kotak Mahindra Bank", "Banks", true],
  ["AXISBANK", "Axis Bank", "Banks", true],
  ["INDUSINDBK", "IndusInd Bank", "Banks", true],
  ["BANKBARODA", "Bank of Baroda", "Banks", true],
  ["PNB", "Punjab National Bank", "Banks", true],
  ["CANBK", "Canara Bank", "Banks", true],
  ["IDFCFIRSTB", "IDFC First Bank", "Banks", true],
  ["FEDERALBNK", "Federal Bank", "Banks", true],
  ["AUBANK", "AU Small Finance Bank", "Banks", true],
  ["RBLBANK", "RBL Bank", "Banks", true],
  ["BANDHANBNK", "Bandhan Bank", "Banks", true],
  ["INDIANB", "Indian Bank", "Banks", true],
  ["UNIONBANK", "Union Bank of India", "Banks", true],
  // Financial Services
  ["BAJFINANCE", "Bajaj Finance", "Financial Services", true],
  ["BAJAJFINSV", "Bajaj Finserv", "Financial Services", true],
  ["JIOFIN", "Jio Financial Services", "Financial Services", true],
  ["SBILIFE", "SBI Life Insurance", "Financial Services", true],
  ["HDFCLIFE", "HDFC Life Insurance", "Financial Services", true],
  ["ICICIPRULI", "ICICI Prudential Life", "Financial Services", true],
  ["ICICIGI", "ICICI Lombard General", "Financial Services", true],
  ["LICI", "Life Insurance Corp of India", "Financial Services", true],
  ["SHRIRAMFIN", "Shriram Finance", "Financial Services", true],
  ["CHOLAFIN", "Cholamandalam Finance", "Financial Services", true],
  ["PFC", "Power Finance Corp", "Financial Services", true],
  ["RECLTD", "REC Ltd", "Financial Services", true],
  ["IRFC", "Indian Railway Finance", "Financial Services", true],
  ["MUTHOOTFIN", "Muthoot Finance", "Financial Services", true],
  ["MANAPPURAM", "Manappuram Finance", "Financial Services", true],
  ["LICHSGFIN", "LIC Housing Finance", "Financial Services", true],
  ["M&MFIN", "Mahindra & Mahindra Fin", "Financial Services", true],
  ["ABCAPITAL", "Aditya Birla Capital", "Financial Services", true],
  ["HDFCAMC", "HDFC Asset Management", "Financial Services", true],
  ["NAM-INDIA", "Nippon Life AMC", "Financial Services", true],
  ["CAMS", "Computer Age Management", "Financial Services", true],
  ["ANGELONE", "Angel One", "Financial Services", true],
  ["MOTILALOFS", "Motilal Oswal Financial", "Financial Services", true],
  ["BSE", "BSE Ltd", "Financial Services", true],
  ["MCX", "Multi Commodity Exchange", "Financial Services", true],
  ["CDSL", "Central Depository Services", "Financial Services", true],
  ["POLICYBZR", "PB Fintech", "Financial Services", true],
  ["PNBHOUSING", "PNB Housing Finance", "Financial Services", true],
  ["POONAWALLA", "Poonawalla Fincorp", "Financial Services", true],
  // IT
  ["TCS", "Tata Consultancy Services", "IT", true],
  ["INFY", "Infosys", "IT", true],
  ["HCLTECH", "HCL Technologies", "IT", true],
  ["WIPRO", "Wipro", "IT", true],
  ["TECHM", "Tech Mahindra", "IT", true],
  ["LTM", "LTIMindtree", "IT", true, ["LTIM"]],
  ["PERSISTENT", "Persistent Systems", "IT", true],
  ["COFORGE", "Coforge", "IT", true],
  ["MPHASIS", "Mphasis", "IT", true],
  ["LTTS", "L&T Technology Services", "IT", true],
  ["KPITTECH", "KPIT Technologies", "IT", true],
  ["TATAELXSI", "Tata Elxsi", "IT", true],
  ["OFSS", "Oracle Financial Services", "IT", true],
  ["CYIENT", "Cyient", "IT", true],
  // Energy
  ["RELIANCE", "Reliance Industries", "Energy", true],
  ["ONGC", "Oil & Natural Gas Corp", "Energy", true],
  ["IOC", "Indian Oil Corp", "Energy", true],
  ["BPCL", "Bharat Petroleum", "Energy", true],
  ["HINDPETRO", "Hindustan Petroleum", "Energy", true],
  ["GAIL", "GAIL India", "Energy", true],
  ["PETRONET", "Petronet LNG", "Energy", true],
  ["OIL", "Oil India", "Energy", true],
  ["IGL", "Indraprastha Gas", "Energy", true],
  ["MGL", "Mahanagar Gas", "Energy", true],
  ["ATGL", "Adani Total Gas", "Energy", true],
  ["COALINDIA", "Coal India", "Energy", true],
  // Power
  ["NTPC", "NTPC Ltd", "Power", true],
  ["POWERGRID", "Power Grid Corp", "Power", true],
  ["TATAPOWER", "Tata Power", "Power", true],
  ["ADANIPOWER", "Adani Power", "Power", true],
  ["ADANIGREEN", "Adani Green Energy", "Power", true],
  ["ADANIENSOL", "Adani Energy Solutions", "Power", true],
  ["JSWENERGY", "JSW Energy", "Power", true],
  ["NHPC", "NHPC Ltd", "Power", true],
  ["SJVN", "SJVN Ltd", "Power", true],
  ["TORNTPOWER", "Torrent Power", "Power", true],
  ["CESC", "CESC Ltd", "Power", true],
  ["SUZLON", "Suzlon Energy", "Power", true],
  ["INOXWIND", "Inox Wind", "Power", true],
  ["WAAREEENER", "Waaree Energies", "Power", true],
  // Metals
  ["TATASTEEL", "Tata Steel", "Metals", true],
  ["JSWSTEEL", "JSW Steel", "Metals", true],
  ["HINDALCO", "Hindalco Industries", "Metals", true],
  ["VEDL", "Vedanta", "Metals", true],
  ["NMDC", "NMDC Ltd", "Metals", true],
  ["SAIL", "Steel Authority of India", "Metals", true],
  ["JINDALSTEL", "Jindal Steel & Power", "Metals", true],
  ["NATIONALUM", "National Aluminium", "Metals", true],
  ["HINDZINC", "Hindustan Zinc", "Metals", true],
  ["APLAPOLLO", "APL Apollo Tubes", "Metals", true],
  ["RATNAMANI", "Ratnamani Metals", "Metals", true],
  ["WELCORP", "Welspun Corp", "Metals", true],
  // Auto
  ["MARUTI", "Maruti Suzuki", "Auto", true],
  ["TMCV", "Tata Motors (commercial)", "Auto", true, ["TATAMOTORS"]],
  ["TMPV", "Tata Motors (passenger)", "Auto", true],
  ["M&M", "Mahindra & Mahindra", "Auto", true],
  ["BAJAJ-AUTO", "Bajaj Auto", "Auto", true],
  ["EICHERMOT", "Eicher Motors", "Auto", true],
  ["HEROMOTOCO", "Hero MotoCorp", "Auto", true],
  ["TVSMOTOR", "TVS Motor Company", "Auto", true],
  ["ASHOKLEY", "Ashok Leyland", "Auto", true],
  ["MOTHERSON", "Samvardhana Motherson", "Auto", true],
  ["BOSCHLTD", "Bosch India", "Auto", true],
  ["BHARATFORG", "Bharat Forge", "Auto", true],
  ["SONACOMS", "Sona BLW Precision", "Auto", true],
  ["SUNDRMFAST", "Sundram Fasteners", "Auto", true],
  ["UNOMINDA", "Uno Minda", "Auto", true],
  ["MRF", "MRF Ltd", "Auto", true],
  ["BALKRISIND", "Balkrishna Industries", "Auto", true],
  ["APOLLOTYRE", "Apollo Tyres", "Auto", true],
  ["CEATLTD", "CEAT Ltd", "Auto", true],
  ["EXIDEIND", "Exide Industries", "Auto", true],
  ["ENDURANCE", "Endurance Technologies", "Auto", true],
  ["TIINDIA", "Tube Investments of India", "Auto", true],
  // FMCG
  ["HINDUNILVR", "Hindustan Unilever", "FMCG", true],
  ["ITC", "ITC Ltd", "FMCG", true],
  ["NESTLEIND", "Nestle India", "FMCG", true],
  ["BRITANNIA", "Britannia Industries", "FMCG", true],
  ["DABUR", "Dabur India", "FMCG", true],
  ["MARICO", "Marico Ltd", "FMCG", true],
  ["GODREJCP", "Godrej Consumer Products", "FMCG", true],
  ["COLPAL", "Colgate-Palmolive India", "FMCG", true],
  ["TATACONSUM", "Tata Consumer Products", "FMCG", true],
  ["VBL", "Varun Beverages", "FMCG", true],
  ["EMAMILTD", "Emami Ltd", "FMCG", true],
  ["PATANJALI", "Patanjali Foods", "FMCG", true],
  ["JYOTHYLAB", "Jyothy Labs", "FMCG", true],
  ["HATSUN", "Hatsun Agro Product", "FMCG", false],
  // Pharma
  ["SUNPHARMA", "Sun Pharmaceutical", "Pharma", true],
  ["DRREDDY", "Dr Reddy's Labs", "Pharma", true],
  ["CIPLA", "Cipla Ltd", "Pharma", true],
  ["DIVISLAB", "Divi's Laboratories", "Pharma", true],
  ["AUROPHARMA", "Aurobindo Pharma", "Pharma", true],
  ["LUPIN", "Lupin Ltd", "Pharma", true],
  ["TORNTPHARM", "Torrent Pharmaceuticals", "Pharma", true],
  ["ALKEM", "Alkem Laboratories", "Pharma", true],
  ["MANKIND", "Mankind Pharma", "Pharma", true],
  ["ZYDUSLIFE", "Zydus Lifesciences", "Pharma", true],
  ["GLENMARK", "Glenmark Pharmaceuticals", "Pharma", true],
  ["BIOCON", "Biocon Ltd", "Pharma", true],
  ["LAURUSLABS", "Laurus Labs", "Pharma", true],
  ["GLAND", "Gland Pharma", "Pharma", true],
  ["IPCALAB", "Ipca Laboratories", "Pharma", true],
  ["ABBOTINDIA", "Abbott India", "Pharma", true],
  ["SYNGENE", "Syngene International", "Pharma", true],
  // Healthcare
  ["APOLLOHOSP", "Apollo Hospitals", "Healthcare", true],
  ["MAXHEALTH", "Max Healthcare Institute", "Healthcare", true],
  ["FORTIS", "Fortis Healthcare", "Healthcare", true],
  ["LALPATHLAB", "Dr Lal PathLabs", "Healthcare", true],
  ["METROPOLIS", "Metropolis Healthcare", "Healthcare", false],
  ["KALYANKJIL", "Kalyan Jewellers", "Healthcare", true],
  // Consumer
  ["TITAN", "Titan Company", "Consumer", true],
  ["DMART", "Avenue Supermarts", "Consumer", true],
  ["TRENT", "Trent Ltd", "Consumer", true],
  ["ETERNAL", "Eternal (Zomato)", "Consumer", true],
  ["SWIGGY", "Swiggy Ltd", "Consumer", true],
  ["NYKAA", "FSN E-Commerce (Nykaa)", "Consumer", true],
  ["PAGEIND", "Page Industries", "Consumer", true],
  ["ABFRL", "Aditya Birla Fashion", "Consumer", true],
  ["VOLTAS", "Voltas Ltd", "Consumer", true],
  ["BLUESTARCO", "Blue Star Ltd", "Consumer", true],
  ["CROMPTON", "Crompton Greaves Consumer", "Consumer", true],
  ["WHIRLPOOL", "Whirlpool of India", "Consumer", false],
  ["DIXON", "Dixon Technologies", "Consumer", true],
  ["POLYCAB", "Polycab India", "Consumer", true],
  ["HAVELLS", "Havells India", "Consumer", true],
  ["VGUARD", "V-Guard Industries", "Consumer", false],
  ["PVRINOX", "PVR INOX Ltd", "Consumer", true],
  ["INDIGO", "InterGlobe Aviation", "Consumer", true],
  ["JUBLFOOD", "Jubilant FoodWorks", "Consumer", true],
  ["DEVYANI", "Devyani International", "Consumer", false],
  // Telecom & Media
  ["BHARTIARTL", "Bharti Airtel", "Telecom", true],
  ["IDEA", "Vodafone Idea", "Telecom", true],
  ["INDUSTOWER", "Indus Towers", "Telecom", true],
  ["SUNTV", "Sun TV Network", "Media", true],
  ["ZEEL", "Zee Entertainment", "Media", true],
  // Cement & building materials
  ["ULTRACEMCO", "UltraTech Cement", "Cement", true],
  ["GRASIM", "Grasim Industries", "Cement", true],
  ["SHREECEM", "Shree Cement", "Cement", true],
  ["AMBUJACEM", "Ambuja Cements", "Cement", true],
  ["ACC", "ACC Ltd", "Cement", true],
  ["DALBHARAT", "Dalmia Bharat", "Cement", true],
  ["RAMCOCEM", "Ramco Cements", "Cement", true],
  ["JKCEMENT", "JK Cement", "Cement", true],
  ["BIRLACORPN", "Birla Corporation", "Cement", false],
  ["ASIANPAINT", "Asian Paints", "Cement", true],
  ["BERGEPAINT", "Berger Paints", "Cement", true],
  ["KANSAINER", "Kansai Nerolac Paints", "Cement", true],
  ["PIDILITIND", "Pidilite Industries", "Cement", true],
  ["SUPREMEIND", "Supreme Industries", "Cement", true],
  ["ASTRAL", "Astral Ltd", "Cement", true],
  ["FINPIPE", "Finolex Industries", "Cement", false],
  // Chemicals & fertilizers
  ["UPL", "UPL Ltd", "Chemicals", true],
  ["PIIND", "PI Industries", "Chemicals", true],
  ["SRF", "SRF Ltd", "Chemicals", true],
  ["AARTIIND", "Aarti Industries", "Chemicals", true],
  ["DEEPAKNTR", "Deepak Nitrite", "Chemicals", true],
  ["TATACHEM", "Tata Chemicals", "Chemicals", true],
  ["GHCL", "GHCL Ltd", "Chemicals", false],
  ["COROMANDEL", "Coromandel International", "Chemicals", true],
  ["CHAMBLFERT", "Chambal Fertilisers", "Chemicals", true],
  ["GSFC", "Gujarat State Fertilizers", "Chemicals", false],
  ["GNFC", "Gujarat Narmada Valley", "Chemicals", false],
  ["RCF", "Rashtriya Chemicals", "Chemicals", false],
  ["FACT", "Fertilisers & Chemicals", "Chemicals", false],
  ["BAYERCROP", "Bayer CropScience", "Chemicals", false],
  ["SUMICHEM", "Sumitomo Chemical India", "Chemicals", false],
  ["ATUL", "Atul Ltd", "Chemicals", false],
  // Capital goods, engineering, defence
  ["LT", "Larsen & Toubro", "Capital Goods", true],
  ["SIEMENS", "Siemens Ltd", "Capital Goods", true],
  ["ABB", "ABB India", "Capital Goods", true],
  ["HAL", "Hindustan Aeronautics", "Capital Goods", true],
  ["BEL", "Bharat Electronics", "Capital Goods", true],
  ["BDL", "Bharat Dynamics", "Capital Goods", true],
  ["MAZDOCK", "Mazagon Dock Shipbuilders", "Capital Goods", true],
  ["COCHINSHIP", "Cochin Shipyard", "Capital Goods", true],
  ["GRSE", "Garden Reach Shipbuilders", "Capital Goods", true],
  ["DATAPATTNS", "Data Patterns India", "Capital Goods", true],
  ["CGPOWER", "CG Power & Industrial", "Capital Goods", true],
  ["CUMMINSIND", "Cummins India", "Capital Goods", true],
  ["THERMAX", "Thermax Ltd", "Capital Goods", true],
  ["AIAENG", "AIA Engineering", "Capital Goods", true],
  ["KEI", "KEI Industries", "Capital Goods", true],
  ["TIMKEN", "Timken India", "Capital Goods", false],
  ["SCHAEFFLER", "Schaeffler India", "Capital Goods", true],
  ["GRINDWELL", "Grindwell Norton", "Capital Goods", false],
  ["CARBORUNIV", "Carborundum Universal", "Capital Goods", false],
  ["BHEL", "Bharat Heavy Electricals", "Capital Goods", true],
  ["INGERRAND", "Ingersoll Rand India", "Capital Goods", false],
  ["KIRLOSENG", "Kirloskar Brothers", "Capital Goods", false],
  // Infra, construction, logistics
  ["ADANIENT", "Adani Enterprises", "Infra", true],
  ["ADANIPORTS", "Adani Ports & SEZ", "Infra", true],
  ["GMRAIRPORT", "GMR Airports", "Infra", true],
  ["IRB", "IRB Infrastructure", "Infra", true],
  ["NBCC", "NBCC India", "Infra", true],
  ["NCC", "NCC Ltd", "Infra", true],
  ["PNCINFRA", "PNC Infratech", "Infra", false],
  ["CONCOR", "Container Corp of India", "Logistics", true],
  ["IRCTC", "IRCTC Ltd", "Logistics", true],
  ["RVNL", "Rail Vikas Nigam", "Infra", true],
  ["DELHIVERY", "Delhivery Ltd", "Logistics", true],
  ["BLUEDART", "Blue Dart Express", "Logistics", false],
  // Realty
  ["DLF", "DLF Ltd", "Realty", true],
  ["GODREJPROP", "Godrej Properties", "Realty", true],
  ["OBEROIRLTY", "Oberoi Realty", "Realty", true],
  ["PRESTIGE", "Prestige Estates", "Realty", true],
  ["PHOENIXLTD", "Phoenix Mills", "Realty", true],
  ["BRIGADE", "Brigade Enterprises", "Realty", true],
  ["SOBHA", "Sobha Ltd", "Realty", false],
  ["LODHA", "Macrotech Developers", "Realty", true],
];

export interface UniverseEntry {
  symbol: string;
  name: string;
  sector: string;
  fno: boolean;
  /** Predecessor tickers this name traded under inside the data window. */
  aliases: string[];
}

export const UNIVERSE: UniverseEntry[] = ENTRIES.map(([symbol, name, sector, fno, aliases]) => ({
  symbol,
  name,
  sector,
  fno,
  aliases: aliases ?? [],
}));
